export {default as Checkout} from './Checkout'
export {default as Detail} from './Detail'
export {default as Earphones} from './Earphones'
export {default as Headphones} from './Headphones'
export {default as Home} from './Home'
export {default as Speakers} from './Speakers'